### ISSUE TITLE
Running a shell/bash script on startup

### ISSUE THREAD

**Issue by Hekit** [ufal/lindat-billing#4]
Preparing a script that would be run on startup (npm start?). 
One of the uses would bt it creating a database or renewing it if it already existed.
The problem lies in making it work both on windows and unix or at least not crash when trying to run unix script on win.

**Comment by vidiecan** [comment]
what about running a js script instead - you can make it os agnostic pretty easily

**Comment by Hekit** [comment]
Actually windows is not really needed and therefore closing.
